# Configuration file for the DDPGP model with N-GPs=x and expert-size (N-local)=y
N: 21497
N_train: 18057
train_per: 0.84
test_per: 0.16 # 84% avoids noise burst at the end of data
N_local: 1128
NGPs: 16
kernel: RBF + WhiteKernel
ignored_regions: []
DP_hyper:
  init_K: 7
  DP_max_iter:
    - [300]

length_scale:
  initial:
  - [800, 800, 800, 800, 800, 800, 800, 800, 800, 800]
  bounds:
  - [0.1, 100000]
  optimal:
  - [0.321, 1.66e+04, 1.61, 1.87, 9.05e+03, 0.576, 1.05, 694, 0.78, 0.401]

noise:
  level:
  - 0.61
  bounds:
    - [0.00001, 1]